name:                haskell-echobot
version:             0.0.0.0
github:              "ISVios/haskell-echobot"
license:             BSD3
author:              "Zhemanov Alexandr (IsVios)"
maintainer:          "i.svoboda.vios@gmail.com"
copyright:           "2021 IsVios"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            EchoBot
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ISVios/haskell-echobot#readme>

dependencies:
- base >= 4.7 && < 5
- ini          # ini parser
- aeson        # json parser
- directory    # exist file test
- http-conduit # http req
- containers   # Map type
- hspec        # for testing
library:
  source-dirs: src

executables:
  haskell-echobot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-echobot

tests:
  haskell-echobot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-echobot
